### ISSUE TITLE
Software crash on some PNG usage

### ISSUE THREAD

**Issue by Benehiko** [Benehiko/ocr-core#1]
Currently experiencing some software crashes using a PNG image in our processing.

`run:
OpenCV Error: Assertion failed (_filter == CV_GAUSSIAN_5x5 && src.type() == dst.type()) in cvPyrDown, file /projects/bytedeco/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.4.0/modules/imgproc/src/pyramids.cpp, line 1645
Exception in thread "main" java.lang.RuntimeException: /projects/bytedeco/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.4.0/modules/imgproc/src/pyramids.cpp:1645: error: (-215) _filter == CV_GAUSSIAN_5x5 && src.type() == dst.type() in function cvPyrDown

	at org.bytedeco.javacpp.opencv_imgproc.cvPyrDown(Native Method)
	at ocr.core.OcrShapes.find_squares(OcrShapes.java:109)
	at ocr.core.OcrShapes.recognise_shapes(OcrShapes.java:73)
	at ocr.core.OcrCore.openCv(OcrCore.java:82)
	at ocr.core.OcrCore.process_image(OcrCore.java:55)
	at ocr.core.TestDriver.main(TestDriver.java:19)
/home/benehiko/.cache/netbeans/8.2/executor-snippets/run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)`

**Comment by Benehiko** [comment]
Might be caused by the transparent nature of the png's background

**Comment by Benehiko** [comment]
This might be irrelevant...
